name: gokong build
on:
  push:
    branches:
      - develop
      - stage
      - master
      - 'feature/*'

jobs:
  build:
    name: building gokong
    runs-on: [self-hosted, linux, amd64, small, spot]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '1.24' # The Go version to download (if necessary) and use.
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.11.4'  # The Terraform version to download (if necessary) and use.
    - run: go version

    - name: Run test
      run: make test

